#:schema node_modules/wrangler/config-schema.json
name = "bolt"
main = "./worker-configuration.d.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"
send_metrics = false

[build]
command = "npm run build"
watch_dir = "app"

[vars]
NODE_ENV = "development"
